// SPDX-FileCopyrightText: 2026 iliyaj
// SPDX-License-Identifier: GPL-3.0-or-later

//! Creates the first durable profile from the compositor's live output state.

use crate::config::{persistence, Config, OutputConfig, Profile, Transform};
use crate::wayland::{OutputHead, OutputManager, OutputMode};
use anyhow::{anyhow, Context, Result};
use std::path::Path;
use wayland_client::protocol::wl_output;

/// Discover the current topology and create a configuration without overwriting one.
pub async fn initialize_config(path: &Path) -> Result<()> {
    if tokio::fs::symlink_metadata(path).await.is_ok() {
        return Err(anyhow!(
            "Refusing to replace existing config: {}",
            path.display()
        ));
    }

    let mut output_manager = OutputManager::new();
    output_manager.initialize().await?;
    output_manager.refresh_outputs().await?;
    if !output_manager.is_available() {
        return Err(anyhow!(
            "The compositor does not provide wlr-output-management"
        ));
    }

    let heads: Vec<_> = output_manager.get_heads().into_iter().cloned().collect();
    let config = config_from_heads(&heads)?;
    config.validate()?;
    config.validate_environment().await?;
    let source = format!(
        "# Generated by `nagame init` from the live Wayland output configuration.\n{}",
        config.to_toml()?
    );
    persistence::create_new(path, &source)
        .await
        .with_context(|| format!("Failed to initialize {}", path.display()))
}

fn config_from_heads(heads: &[OutputHead]) -> Result<Config> {
    if heads.is_empty() {
        return Err(anyhow!("The compositor reported no connected outputs"));
    }

    let outputs = heads
        .iter()
        .map(|head| {
            let mode = if head.enabled {
                Some(persistent_mode(head.current_mode.as_ref().ok_or_else(
                    || {
                        anyhow!(
                            "Enabled output '{}' has no current advertised mode",
                            head.name
                        )
                    },
                )?))
            } else {
                None
            };
            Ok(OutputConfig {
                name: head.name.clone(),
                enabled: head.enabled,
                mode,
                scale: head.enabled.then_some(head.scale),
                position: head.position.map(|(x, y)| [x, y]),
                transform: head.enabled.then_some(config_transform(head.transform)),
                adaptive_sync: head.adaptive_sync,
            })
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(Config {
        profiles: vec![Profile {
            name: "current-displays".to_string(),
            outputs,
            exec: Vec::new(),
            wallpaper: None,
            wallpaper_dir: None,
        }],
    })
}

fn persistent_mode(mode: &OutputMode) -> String {
    let whole = mode.refresh_mhz / 1000;
    let fraction = mode.refresh_mhz.rem_euclid(1000);
    if fraction == 0 {
        format!("{}x{}@{}", mode.width, mode.height, whole)
    } else {
        let refresh = format!("{}.{:03}", whole, fraction)
            .trim_end_matches('0')
            .to_string();
        format!("{}x{}@{}", mode.width, mode.height, refresh)
    }
}

fn config_transform(transform: wl_output::Transform) -> Transform {
    match transform {
        wl_output::Transform::Normal => Transform::Normal,
        wl_output::Transform::_90 => Transform::Rotate90,
        wl_output::Transform::_180 => Transform::Rotate180,
        wl_output::Transform::_270 => Transform::Rotate270,
        wl_output::Transform::Flipped => Transform::Flipped,
        wl_output::Transform::Flipped90 => Transform::Flipped90,
        wl_output::Transform::Flipped180 => Transform::Flipped180,
        wl_output::Transform::Flipped270 => Transform::Flipped270,
        _ => Transform::Normal,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn head(name: &str, refresh_mhz: i32) -> OutputHead {
        let mode = OutputMode {
            width: 2560,
            height: 1440,
            refresh_mhz,
            preferred: true,
        };
        OutputHead {
            id: 1,
            name: name.to_string(),
            description: String::new(),
            physical_size: None,
            position: Some((10, 20)),
            transform: wl_output::Transform::_90,
            scale: 1.25,
            enabled: true,
            modes: vec![mode.clone()],
            current_mode: Some(mode.clone()),
            preferred_mode: Some(mode),
            make: String::new(),
            model: String::new(),
            serial_number: String::new(),
            adaptive_sync: Some(true),
        }
    }

    #[test]
    fn captures_live_output_properties_and_exact_refresh() {
        let config = config_from_heads(&[head("DP-1", 143_973)]).unwrap();
        let output = &config.profiles[0].outputs[0];
        assert_eq!(config.profiles[0].name, "current-displays");
        assert_eq!(output.name, "DP-1");
        assert_eq!(output.mode.as_deref(), Some("2560x1440@143.973"));
        assert_eq!(output.position, Some([10, 20]));
        assert_eq!(output.scale, Some(1.25));
        assert!(matches!(output.transform, Some(Transform::Rotate90)));
        assert_eq!(output.adaptive_sync, Some(true));
    }

    #[test]
    fn rejects_enabled_output_without_a_current_mode() {
        let mut output = head("DP-1", 60_000);
        output.current_mode = None;
        assert!(config_from_heads(&[output])
            .unwrap_err()
            .to_string()
            .contains("no current advertised mode"));
    }

    #[test]
    fn rejects_empty_topology() {
        assert!(config_from_heads(&[]).is_err());
    }
}
